name: 'Push branch to a new repo'
description: 'Pushes a branch to a new repository'

inputs:
  github-token:
    required: true
    description: 'The github token'
  repo-deploy-key:
    required: true
    description: 'The secret for the repository we're pushing to'
  repo-owner:
    required: true
    description: 'The owner of the repo we're pushing to
  repo-name:
    required: true
    description: 'The name of the repository'

runs:
  using: 'node12'
  main: 'index.js'