on:
  workflow_dispatch:

jobs:
  create_repo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/create-repo
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        repo-deploy-key: ${{ secrets.TARGET_DEPLOY }}
        repo-owner: 'hectorsector'
        repo-name: 'ubiquitous-octo-potato'